import { Box } from '@mui/material'
import axios from 'axios'
import { GetServerSideProps } from 'next'
import Head from 'next/head'
import { ProductType } from 'src/types/product'
import HomePage from 'src/views/pages/home'

interface HomeProps {
  products: ProductType[]
}

const API_URL = process.env.NEXT_PUBLIC_API_BASE_URL

export default function Home({ products }: HomeProps) {
  return (
    <>
      <Head>
        <title>Thổ mộc</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Box sx={{ mx: { xs: 2, md: 6 } }}>
        <HomePage products={products} />
      </Box>
    </>
  )
}

export const getServerSideProps: GetServerSideProps<HomeProps> = async context => {
  const acceptLanguage = context.req.headers['accept-language'] || 'en'

  const baseLang = acceptLanguage.split('-')[0].split(',')[0].toLowerCase()

  try {
    const response = await axios.get(`${API_URL}/product`, {
      params: { page: 1, limit: 20 },
      headers: {
        'Accept-Language': baseLang // Send normalized base language
      }
    })

    const products: ProductType[] = response.data?.data ?? []

    return {
      props: {
        products: JSON.parse(JSON.stringify(products))
      }
    }
  } catch (error) {
    console.error('Failed to fetch products:', error)

    return {
      props: {
        products: []
      }
    }
  }
}

// Home.getLayout = (page: React.ReactNode) => <>{page}</>
Home.guestGuard = false
Home.authGuard = false
