'use client'
import Head from 'next/head'
import Button from '@mui/material/Button'
import { useTheme } from '@emotion/react'
import { Box, Typography } from '@mui/material'
import CustomTextField from 'src/components/text-field'

export default function Home() {
  const theme = useTheme()

  return (
    <>
      <Head>
        <title>Thổ mộc</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Box sx={{ margin: 6, width: '200px' }}>
        <CustomTextField id='outlined-multiline-flexible' label='Name' />
      </Box>
    </>
  )
}
