import { Box } from '@mui/material'
import axios from 'axios'
import { GetServerSideProps } from 'next'
import Head from 'next/head'
import { useRouter } from 'next/router'
import { ProductType } from 'src/types/product'
import { CategoryWithTranslationsType } from 'src/types/category'
import HomePage from 'src/views/pages/home'

interface HomeProps {
  products: ProductType[]
  totalPages: number
  currentPage: number
  categories: CategoryWithTranslationsType[]
}

const API_URL = process.env.NEXT_PUBLIC_API_BASE_URL
const LIMIT = 10

export default function Home({ products, totalPages, currentPage, categories }: HomeProps) {
  const router = useRouter()

  const handlePageChange = (page: number) => {
    router.push({ pathname: '/', query: { page } }, undefined, { scroll: true })
  }

  const handleCategoryClick = (categoryId: number) => {
    router.push(`/category/${categoryId}`)
  }

  return (
    <>
      <Head>
        <title>Thổ mộc</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Box sx={{ mx: { xs: 2, md: 6 } }}>
        <HomePage
          products={products}
          totalPages={totalPages}
          currentPage={currentPage}
          onPageChange={handlePageChange}
          categories={categories}
          onCategoryClick={handleCategoryClick}
        />
      </Box>
    </>
  )
}

export const getServerSideProps: GetServerSideProps<HomeProps> = async context => {
  const acceptLanguage = context.req.headers['accept-language'] || 'en'
  const baseLang = acceptLanguage.split('-')[0].split(',')[0].toLowerCase()

  // Lấy page từ query string, mặc định là 1
  const page = Number(context.query.page) || 1

  try {
    const [productResponse, categoryResponse] = await Promise.all([
      axios.get(`${API_URL}/product`, {
        params: { page, limit: LIMIT },
        headers: {
          'Accept-Language': baseLang
        }
      }),
      axios.get(`${API_URL}/category`, {
        headers: {
          'Accept-Language': baseLang
        }
      })
    ])

    const products: ProductType[] = productResponse.data?.data ?? []
    const totalPages: number = productResponse.data?.totalPages ?? 1
    const categories: CategoryWithTranslationsType[] = categoryResponse.data?.data ?? []

    return {
      props: {
        products: JSON.parse(JSON.stringify(products)),
        totalPages,
        currentPage: page,
        categories: JSON.parse(JSON.stringify(categories))
      }
    }
  } catch (error) {
    console.error('Failed to fetch data:', error)

    return {
      props: {
        products: [],
        totalPages: 1,
        currentPage: 1,
        categories: []
      }
    }
  }
}

Home.guestGuard = false
Home.authGuard = false
